/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResidentSignupRouteImport } from './routes/resident-signup'
import { Route as IndexRouteImport } from './routes/index'

const ResidentSignupRoute = ResidentSignupRouteImport.update({
  id: '/resident-signup',
  path: '/resident-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resident-signup': typeof ResidentSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resident-signup': typeof ResidentSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resident-signup': typeof ResidentSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/resident-signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/resident-signup'
  id: '__root__' | '/' | '/resident-signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResidentSignupRoute: typeof ResidentSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resident-signup': {
      id: '/resident-signup'
      path: '/resident-signup'
      fullPath: '/resident-signup'
      preLoaderRoute: typeof ResidentSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResidentSignupRoute: ResidentSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
